Languages 💬:
  - Fortran
  - C/C++
  - Julia
  - Python
  - Other Languages

Parallelism 🔀:
  - OpenMP
  - MPI
  - I/O
  - Hybrid

GPU 🎮:
  - OpenMP offload
  - OpenACC
  - CUDA
  - HIP
  - Other GPU

Performance 📊:
  - Performance Engineering
  - Performance Analysis
  - Tools

Development Skills 🪒:
  - UNIX
  - Git
  - Containers


Other 📦:
  - Professional Skills
  - Other

Community 🎉:
  - Seminar
  - Community

Getting started 👣:
  - Intro to HPC